# Generated by Django 3.1.6 on 2021-05-31 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=250)),
                ('phone_number', models.IntegerField(default='')),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_name', models.CharField(default='', max_length=100)),
                ('UserId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EList.login')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_name', models.CharField(default='', max_length=100)),
                ('diary_date', models.DateField(default='2021-05-20')),
                ('mood', models.CharField(default='', max_length=150)),
                ('achi', models.CharField(default='', max_length=150)),
                ('entry', models.TextField(default='')),
                ('DiaId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EList.list')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_name', models.CharField(default='', max_length=100)),
                ('favorite', models.CharField(default='', max_length=500)),
                ('date_added', models.DateField(default='2021-05-20')),
                ('DiaId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EList.list')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveAuthenticate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_name', models.CharField(default='', max_length=100)),
                ('four_digit_passcode', models.CharField(default='', max_length=4)),
                ('DiaId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EList.list')),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_name', models.CharField(default='', max_length=100)),
                ('archive', models.CharField(default='', max_length=500)),
                ('date_added', models.DateField(default='2021-05-20')),
                ('ArchiveId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EList.archiveauthenticate')),
            ],
        ),
    ]
