# Generated by Django 3.1.6 on 2021-05-15 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_date', models.CharField(default='', max_length=25)),
                ('mood', models.CharField(default='', max_length=25)),
                ('achi', models.CharField(default='', max_length=1000)),
                ('entry', models.CharField(default='', max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('DiaId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EList.list')),
            ],
        ),
    ]
