# Generated by Django 3.1.6 on 2021-05-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='achi',
        ),
        migrations.RemoveField(
            model_name='list',
            name='diary_date',
        ),
        migrations.RemoveField(
            model_name='list',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='list',
            name='mood',
        ),
        migrations.AddField(
            model_name='item',
            name='achi',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='diary_date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='entry',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='mood',
            field=models.TextField(default=''),
        ),
    ]
