# Generated by Django 3.1.6 on 2021-05-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='diary_date',
        ),
        migrations.AlterField(
            model_name='item',
            name='diary_date',
            field=models.DateField(),
        ),
    ]
