# Generated by Django 3.1.6 on 2021-05-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EList', '0002_auto_20210518_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='diary_date',
            field=models.DateField(blank=True, default='2021-05-20'),
        ),
    ]
