# Generated by Django 3.1.6 on 2021-05-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EList', '0002_auto_20210515_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='diary_name',
        ),
    ]
