# Generated by Django 3.1.6 on 2021-04-30 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EList', '0005_auto_20210430_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list',
            new_name='DiaId',
        ),
    ]
